### ISSUE TITLE
Issues Building on Windows

### ISSUE THREAD

**Issue by smmathews** [anttisalonen/hogre#1]
I've been attempting to build this on windows, and here's the solutions and problems I'm having:

1) ogre.list references GLX. In windows this should be WIN32 instead. This would require selectively choosing GLX/WIN32 based on input from the user.

2) I needed to add WIN32/OgreConfigDialogImp.h and WIN32/OgreErrorDialogImp.h to ogre.list in order to start the haskell files compiling. 

3) I needed to make my own OGRE.pc file, as one is not created when OGRE sdks are installed in windows. It might be helpful to include a .pc file with a readme to help windows users set this up correctly.

3) When compiling Graphics.Ogre.HOgre, I get the following build error:
in file included from res\cgen\OgreWindowEventUtilities.cpp:2:0:
res\cgen\OgreWindowEventUtilities.h:4:23:
    OGRE/Ogre.h: No such file or directory

**Comment by anttisalonen** [comment]
Hi smmathews,

thanks for reporting this and for the solutions.

I fixed the issues by adjusting the cabal setup - there are now different configurations for Windows and non-Windows platforms, and cabal will detect which one it's running on and choose the correct configuration. I also dropped the requirement to use pkg-config on Windows, so that the include and library paths to Ogre and Boost must be configured using the following:

cabal install [-v2] --extra-include-dirs=path/to/include/OGRE --extra-include-dirs=path/to/boost_1_44 --extra-lib-dirs=path/to/OGRE/lib/release

I've pushed the changes to git, and could compile hogre on Windows using GHC 6.12.3. Could you fetch the latest revision and see if it works for you too? You'll just need to supply the include and lib dirs to Ogre and Boost as described above.

On compiling hogre-examples on Windows I ran into linker errors (the examples weren't linked against libstdc++). It may have something to do with GHC ticket 4468 (http://hackage.haskell.org/trac/ghc/ticket/4468) - but I have to look into it.

Antti

**Comment by smmathews** [comment]
Hi Antti,

That solves most of my problems, but Graphs.Ogre.HOgre still fails to compile for me. The error I get is:
/path/to/include/OGRE/WIN32/OgreErrorDialogImp.h:47: error: invalid function declaration

I'm using GHC 6.12.3, boost1.44.0, and the prebuilt 1.7.2 OGRE SDK for MinGW.

Thanks,
Shane

**Comment by anttisalonen** [comment]
Hi Shane,

that's odd, I have the same setup (with the current MinGW with GCC 4.5.0), but for me it compiles through. It looks like a C++ error, what gcc/g++ version are you using?

If you're using 4.5.0 as well, could use run cabal install in verbose mode (-v2) and post the log file? Also, could you make sure your file at OGRE/WIN32/OgreErrorDialogImp.h is the same file I have ([this one](https://bitbucket.org/sinbad/ogre/src/16e772b4f1d0/OgreMain/include/WIN32/OgreErrorDialogImp.h)), and if not, post it here?

Antti

**Comment by smmathews** [comment]
I'm using cygwin with GCC 4.3.4. I'll install MinGW with GCC 4.5.0 and see how that works.

Thanks for all your help

-Shane

**Comment by smmathews** [comment]
Installed mingw with gcc 4.5.0, I then looked at the log and realized the Haskell Platform was automatically using their own copy they shipped with the platform: gcc 4.3.4, so I replaced their mingw with the newest one.

Still getting an error message when compiling, but the mesage is much more elaborate.

Full error message
http://pastebin.com/rKsJVJPa

Log:
http://pastebin.com/dJ17Jn3w

Last bit of cmd output which for some reason didn't go to the log:
http://pastebin.com/MhSSg0Sp

and yes, our OGRE/WIN32/OgreErrorDialogImp.h files match up.

Thanks,

-Shane

**Comment by anttisalonen** [comment]
OK, I think we're getting there - the headers were included in the wrong order in hogre configuration. (It worked on my Windows box because I had accidentally reversed the order.) I pushed a new version of hogre at git, so could you update and retry?

Thanks,

Antti

**Comment by smmathews** [comment]
That did it. Thanks very much Antti, and keep up the good work!

-Shane
